<?php

return [
    'skill' => [
        'create' => [
            'rules' => [
                'title' => 'required|string|max:255',
            ],
            'messages' => [
                'title.required' => 'Skill title is required.',
                'title.string' => 'Skill title must be a string.',
                'title.max' => 'Skill title must not exceed 255 characters.',
            ],
        ],
    ],

    'job' => [
        'create' => [
            'rules' => [
                'title' => 'required|string|max:255',
                'description' => 'required|string',
                'experience' => 'required|string|max:100',
                'salary' => 'required',
                'location' => 'required|string|max:255',
                'extra_info' => 'nullable|string|max:500',
                'company_name' => 'required|string|max:255',
                'company_logo' => 'required|image|mimes:jpg,jpeg,png,gif,webp,svg|max:2048',
                'selectedSkills' => 'required|array|min:1',
                'selectedSkills.*' => 'exists:skills,id',
            ],
            'messages' => [
                'title.required' => 'Job title is required.',
                'title.string' => 'Job title must be a string.',
                'title.max' => 'Job title must not exceed 255 characters.',
                'description.required' => 'Description is required.',
                'description.string' => 'Description must be a valid text.',
                'experience.required' => 'Experience is required.',
                'experience.string' => 'Experience must be a string.',
                'experience.max' => 'Experience must not exceed 100 characters.',
                'salary.required' => 'Salary is required.',
                'location.required' => 'Location is required.',
                'location.string' => 'Location must be a string.',
                'location.max' => 'Location must not exceed 255 characters.',
                'extra_info.string' => 'Extra info must be a string.',
                'extra_info.max' => 'Extra info must not exceed 500 characters.',
                'company_name.required' => 'Company name is required.',
                'company_name.string' => 'Company name must be a string.',
                'company_name.max' => 'Company name must not exceed 255 characters.',
                'company_logo.required' => 'Company logo is required.',
                'company_logo.image' => 'Company logo must be an image file.',
                'company_logo.mimes' => 'Company logo must be a file of type: jpg, jpeg, png, gif, webp, svg.',
                'company_logo.max' => 'Company logo must not exceed 2MB.',
                'selectedSkills.required' => 'At least one skill is required.',
                'selectedSkills.array' => 'Skills must be provided as an array.',
                'selectedSkills.min' => 'At least one skill is required.',
                'selectedSkills.*.exists' => 'One or more selected skills are invalid.',
            ],
        ],
        
        'update' => [
            'rules' => [
                'title' => 'required|string|max:255',
                'description' => 'required|string',
                'experience' => 'required|string|max:100',
                'salary' => 'required',
                'location' => 'required|string|max:255',
                'extra_info' => 'nullable|string|max:500',
                'company_name' => 'required|string|max:255',
                'new_company_logo' => 'nullable|image|mimes:jpg,jpeg,png,gif,webp,svg|max:2048',
                'selectedSkills' => 'required|array|min:1',
                'selectedSkills.*' => 'exists:skills,id',
            ],
            'messages' => [
                'title.required' => 'Job title is required.',
                'title.string' => 'Job title must be a string.',
                'title.max' => 'Job title must not exceed 255 characters.',
                'description.required' => 'Description is required.',
                'description.string' => 'Description must be a valid text.',
                'experience.required' => 'Experience is required.',
                'experience.string' => 'Experience must be a string.',
                'experience.max' => 'Experience must not exceed 100 characters.',
                'salary.required' => 'Salary is required.',
                'location.required' => 'Location is required.',
                'location.string' => 'Location must be a string.',
                'location.max' => 'Location must not exceed 255 characters.',
                'extra_info.string' => 'Extra info must be a string.',
                'extra_info.max' => 'Extra info must not exceed 500 characters.',
                'company_name.required' => 'Company name is required.',
                'company_name.string' => 'Company name must be a string.',
                'company_name.max' => 'Company name must not exceed 255 characters.',
                'new_company_logo.image' => 'Company logo must be an image file.',
                'new_company_logo.mimes' => 'Company logo must be a file of type: jpg, jpeg, png, gif, webp, svg.',
                'new_company_logo.max' => 'Company logo must not exceed 2MB.',
                'selectedSkills.required' => 'At least one skill is required.',
                'selectedSkills.array' => 'Skills must be provided as an array.',
                'selectedSkills.min' => 'At least one skill is required.',
                'selectedSkills.*.exists' => 'One or more selected skills are invalid.',
            ],
        ],
    ],
];